Add map.py and test_map.py
Funiusa/ru-study-python pull request #2
Opened 2023-02-05 16:23 UTC by Funiusa

2023-02-07 02:59 UTC, aleksandr-semenov-dbp requested changes

2023-02-07 02:59 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +        country_filter = filter(lambda movie: len(movie["country"].split(",")) > 1, list_of_movies)
неэффективно использовать split() для подсчета запятых

2023-02-07 12:37 UTC, Funiusa commented on maps/maps.py
> +        country_filter = filter(lambda movie: len(movie["country"].split(",")) > 1, list_of_movies)
После списков, совсем забыл про методы строк. Спасибо

2023-02-08 11:36 UTC, aleksandr-semenov-dbp requested changes

2023-02-08 11:36 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +        country_filter = filter(lambda movie: movie["country"].find(",") > 1, list_of_movies)
`find() > 1` мне тоже не нравится. Ты точно хочешь убедиться что название первой страны длиннее одной буквы?

2023-02-09 21:42 UTC, aleksandr-semenov-dbp approved these changes

2023-02-10 09:46 UTC, merged